### ISSUE TITLE
GONet 251 needs a new SD card. [BUG]

### ISSUE THREAD

**Issue by CTarr** [AdlerFarHorizons/GONet-Ecosystem#26]
**What system is the bug associated with?**
SD card

**Describe the bug**
Currently VERY slow (was stuck on POST to the point of 'no worky').

**To Reproduce**
1. Turn the GONet on.
2. Wait...

**Expected behavior**
1. Turn the GONet on.
2. The GONet will begin imaging within a couple minutes of being turned on.

**Additional context**
Issue was discovered on 5/10 when Laris tried to deploy this GONet (downtown Chicago) to see if it could capture the aurorae.

**Comment by jwalsh2me** [comment]
Need new SD Cards

**Comment by jwalsh2me** [comment]
Replaced SD card, just needs to be focused.  @CTarr @Lauren-Wisbrock 

Might get to it today.

**Comment by jwalsh2me** [comment]
@Lauren-Wisbrock @CTarr GPS Lock on this one was resolved.  The Camera cable was rerouted so that it does not go over the GPS Antenna!
@Walzar
