### ISSUE TITLE
206 Strange Image Cycle Results[BUG]

### ISSUE THREAD

**Issue by Lauren-Wisbrock** [AdlerFarHorizons/GONet-Ecosystem#30]
**What system is the bug associated with?**
Imaging or posting?

**Describe the bug**
Dark frames created sporadically during normal image cycle, see https://drive.google.com/drive/folders/1eq2zrzp4dAv8qVq6YDisfvV-Ii0Ae7Sw 

The lens was left open throughout imaging but it's still creating what look like dark frames.

**To Reproduce**
Run GONet under normal image cycle

**Comment by jwalsh2me** [comment]
Unit is fine, lens can is really loose.  Looking at the images it looks like the lens cap was flipping open closed.  Tape it down for a deployment.

Amir was able to reproduce by blowing on the lens cap.
