### ISSUE TITLE
Calibration Card for 225 issues[BUG]

### ISSUE THREAD

**Issue by Lauren-Wisbrock** [AdlerFarHorizons/GONet-Ecosystem#35]
Was working fine for 12 calibration image cycles on 7/10/24, then it was 'Updating', stopped imaging and is slow or unable to connect with the control center and gallery. Also having difficulty turning off.

**Comment by jwalsh2me** [comment]
Please try and save images if possible.

**Comment by jwalsh2me** [comment]
@Lauren-Wisbrock I have the card, will see if I can salvage the images.  The card definitely is damaged.

**Comment by jwalsh2me** [comment]
Closing this one out.  Was able to recover the images and drop then on Shared Drive.
