### ISSUE TITLE
252 status and no connection to the control center[BUG]

### ISSUE THREAD

**Issue by Lauren-Wisbrock** [AdlerFarHorizons/GONet-Ecosystem#36]
252 was unable to change the camera settings in the control center or load all images in the gallery. Couldn't communicate through the Downloader/tiff Splitter script either.

At one point, it displayed 'Status: cam_err' but after turning on and off again, it now displays 'Status: Ready'

**Comment by jwalsh2me** [comment]
I was able to recreate the issue, replaced the card.  Tested and it is more responsive.
