### ISSUE TITLE
SD Cards for Fall 2023/Winter 2024 GONet Batch

### ISSUE THREAD

**Issue by zhafen** [AdlerFarHorizons/GONet-Ecosystem#5]

**Comment by jwalsh2me** [comment]
Found several bad SD Cards, got at least 3 of the new cameras setup and provisioned.

@Walzar We need new SD Cards to finish.

**Comment by jwalsh2me** [comment]
Carmera cards have been provisioned and updated for the new GONets 251, 252, 253, 254 and 255
